name: Bug Report (FOR DEVELOPERS)
description: Create a report to help us improve
title: 'Bug Report (FOR DEVELOPERS)'
labels: bug

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: Provide a clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: 1. Go to '...' 2. Click on '...' 3. Scroll down to '...' 4. See error
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: false

  - type: input
    id: error-log-link
    attributes:
      label: Error Log Link
      description: Please paste a link to the latest error log where your plugin encountered an issue.
      placeholder: https://pastebin.com/your-error-log
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional context or details that might help diagnose the problem.
    validations:
      required: false
