name: Plugin Merge Request
description: Ask for your plugin to get added to the plugin library
title: 'Plugin Mrege Request'
labels: new plugin

body:
  - type: textarea
    id: plugin-description
    attributes:
      label: What does your plugin do?
      description: A clear description of what your plugin does.
      placeholder: This plugin allows users to look up domain whois information.
    validations:
      required: true

  - type: input
    id: github-link
    attributes:
      label: Link
      description: The GitHub link to your plugin.
      placeholder: https://github.com/yourusername/yourplugin
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional context or notes about your plugin.
    validations:
      required: false

  - type: checkboxes
    id: documentation-agreement
    attributes:
      label: Plugin Compliance
      description: Please confirm the following before submitting your merge request.
      options:
        - label: I have read the wiki for documentation, ensured my plugin works properly without a user needing to fix issues, and my plugin does not break rules.
          required: true
